/* DO NOT MODIFY --- generated by /home/csauer/work/hp/zero/tools/logdef.pl from /home/csauer/work/hp/zero/src/sm/logdef.dat
                     on Sun Nov  6 11:23:50 2016

<std-header orig-src='shore' genfile='true'>

SHORE -- Scalable Heterogeneous Object REpository

Copyright (c) 1994-99 Computer Sciences Department, University of
                      Wisconsin -- Madison
All Rights Reserved.

Permission to use, copy, modify and distribute this software and its
documentation is hereby granted, provided that both the copyright
notice and this permission notice appear in all copies of the
software, derivative works or modified versions, and any portions
thereof, and that both notices appear in supporting documentation.

THE AUTHORS AND THE COMPUTER SCIENCES DEPARTMENT OF THE UNIVERSITY
OF WISCONSIN - MADISON ALLOW FREE USE OF THIS SOFTWARE IN ITS
"AS IS" CONDITION, AND THEY DISCLAIM ANY LIABILITY OF ANY KIND
FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.

This software was developed with support by the Advanced Research
Project Agency, ARPA order number 018 (formerly 8230), monitored by
the U.S. Army Research Laboratory under contract DAAB07-91-C-Q518.
Further funding for this work was provided by DARPA through
Rome Research Laboratory Contract No. F30602-97-2-0247.

*/

#include "w_defines.h"

/*  -- do not edit anything above this line --   </std-header>*/

#include "alloc_page.h"
#include "btree_page_h.h"
#include "stnode_page.h"
#include "w_base.h"
#include "logrec.h"

	case t_comment : 
		((comment_log *) this)->undo(page); 
		break;
	case t_compensate : 
		W_FATAL(eINTERNAL);
		break;
	case t_skip : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_begin : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_bf_tab : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_xct_tab : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_xct_lock : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_restore_tab : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_backup_tab : 
		W_FATAL(eINTERNAL);
		break;
	case t_chkpt_end : 
		W_FATAL(eINTERNAL);
		break;
	case t_add_backup : 
		W_FATAL(eINTERNAL);
		break;
	case t_xct_abort : 
		W_FATAL(eINTERNAL);
		break;
	case t_xct_freeing_space : 
		W_FATAL(eINTERNAL);
		break;
	case t_xct_end : 
		W_FATAL(eINTERNAL);
		break;
	case t_xct_end_group : 
		W_FATAL(eINTERNAL);
		break;
	case t_xct_latency_dump : 
		W_FATAL(eINTERNAL);
		break;
	case t_alloc_page : 
		W_FATAL(eINTERNAL);
		break;
	case t_dealloc_page : 
		W_FATAL(eINTERNAL);
		break;
	case t_create_store : 
		W_FATAL(eINTERNAL);
		break;
	case t_append_extent : 
		W_FATAL(eINTERNAL);
		break;
	case t_loganalysis_begin : 
		W_FATAL(eINTERNAL);
		break;
	case t_loganalysis_end : 
		W_FATAL(eINTERNAL);
		break;
	case t_redo_done : 
		W_FATAL(eINTERNAL);
		break;
	case t_undo_done : 
		W_FATAL(eINTERNAL);
		break;
	case t_restore_begin : 
		W_FATAL(eINTERNAL);
		break;
	case t_restore_segment : 
		W_FATAL(eINTERNAL);
		break;
	case t_restore_end : 
		W_FATAL(eINTERNAL);
		break;
	case t_page_set_to_be_deleted : 
		((page_set_to_be_deleted_log *) this)->undo(page); 
		break;
	case t_page_img_format : 
		((page_img_format_log *) this)->undo(page); 
		break;
	case t_page_evict : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_norec_alloc : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_insert : 
		((btree_insert_log *) this)->undo(page); 
		break;
	case t_btree_insert_nonghost : 
		((btree_insert_nonghost_log *) this)->undo(page); 
		break;
	case t_btree_update : 
		((btree_update_log *) this)->undo(page); 
		break;
	case t_btree_overwrite : 
		((btree_overwrite_log *) this)->undo(page); 
		break;
	case t_btree_ghost_mark : 
		((btree_ghost_mark_log *) this)->undo(page); 
		break;
	case t_btree_ghost_reclaim : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_ghost_reserve : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_foster_adopt : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_foster_merge : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_foster_rebalance : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_foster_rebalance_norec : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_foster_deadopt : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_split : 
		W_FATAL(eINTERNAL);
		break;
	case t_btree_compress_page : 
		W_FATAL(eINTERNAL);
		break;
	case t_tick_sec : 
		W_FATAL(eINTERNAL);
		break;
	case t_tick_msec : 
		W_FATAL(eINTERNAL);
		break;
	case t_benchmark_start : 
		W_FATAL(eINTERNAL);
		break;
	case t_page_write : 
		W_FATAL(eINTERNAL);
		break;
	case t_page_read : 
		W_FATAL(eINTERNAL);
		break;
