/*
 * (c) Copyright 2014, Hewlett-Packard Development Company, LP
 */

/**
 * \file w_error_xmacro.h
 * \brief Error code/message definition in X-Macro style.
 * 
 * \details
 * To add new errors, append a new line at the end.
 * You can also insert at an arbitrary place, but note that the value of existing
 * error codes will change in that case.  If we store error codes somewhere, it
 * might become an issue.  For now we don't do that anywhere, though.
 * For more details, see w_error.h.
 */

X(fcINTERNAL,                 "Internal error")
X(fcOS,                       "Operating system error ")
X(fcFULL,                     "Container is full")
X(fcEMPTY,                    "Container is empty")
X(fcOUTOFMEMORY,              "Malloc failed: out of memory ")
X(fcMMAPFAILED,               "Mmap could not map aligned memory")
X(fcNOTFOUND,                 "Item not found ")
X(fcNOTIMPLEMENTED,           "Feature is not implemented")
X(fcNOSUCHERROR,              "Unknown error code")
X(fcASSERT,                   "Assertion Failed")
X(fcUSERABORT,                "User-requested rollback")
X(stINTERNAL,                 "Internal error")
X(stOS,                       "Operating system error ")
X(stTIMEOUT,                  "Timed out waiting for resource")
X(stBADPATH,                  "Path name cannot be stat()ed")
X(stBADFD,                    "Bad file descriptor for I/O operation, seek, or close")
X(stINUSE,                    "Resource in use")
X(stSHORTIO,                  "Short I/O")
X(stSHORTSEEK,                "Short Seek")
X(eINTERNAL,                  "Internal error")
X(eOS,                        "Operating system error ")
X(eNOTIMPLEMENTED,            "Feature is not implemented")
X(eUSERABORT,                 "User initiated abort")
X(eCRASH,                     "Server told to crash or shutdown immediately")
X(eOUTOFSPACE,                "Out of disk space")
X(eALIGNPARM,                 "Parameter is not aligned")
X(eBADSTID,                   "Malformed or invalid store ID")
X(eNOTFOUND,                  "Item not found ")
X(eFRAMENOTFOUND,             "Frame not found in buffer pool ")
X(eSPACENOTFOUND,             "No page with space in store")
X(eBADPID,                    "Invalid page ID")
X(eBADVOL,                    "Invalid volume ID")
X(eVOLTOOLARGE,               "Volume is too large for device")
X(eDEVTOOLARGE,               "Device is too large for OS file interface")
X(eDEVICEVOLFULL,             "Device cannot hold anymore volumes")
X(eDEVNOTMOUNTED,             "Device is not mounted")
X(eALREADYMOUNTED,            "Device already mounted")
X(eVOLEXISTS,                 "Volume already exists")
X(eBADFORMAT,                 "Volume has bad format")
X(eNVOL,                      "Too many volumes")
X(eEOF,                       "End of scan/record reached")
X(eDUPLICATE,                 "Duplicate entries found")
X(eBADSTORETYPE,              "Bad store type")
X(eBADSTOREFLAGS,             "Bad store flags")
X(eBADNDXTYPE,                "Bad index type")
X(eBADSCAN,                   "Bad scan arguments")
X(eWRONGKEYTYPE,              "Key type unsupported for current index")
X(eNDXNOTEMPTY,               "Index is not empty")
X(eBADKEYTYPESTR,             "Bad key type descriptor")
X(eBADKEY,                    "Bad key value")
X(eBADCMPOP,                  "Bad compare operators")
X(eOUTOFLOGSPACE,             "Out of log space ")
X(eOUTOFMEMORY,               "Malloc failed: out of memory ")
X(eRECWONTFIT,                "Record will not fit")
X(eBADSLOTNUMBER,             "Record ID slot number is bad")
X(eRECUPDATESIZE,             "Record update request is too large")
X(eBADSTART,                  "Start parameter larger than record size")
X(eBADAPPEND,                 "Append size too large for the record")
X(eBADLENGTH,                 "Bad length parameter")
X(eBADSAVEPOINT,              "Bad save point ")
X(ePAGECHANGED,               "Page has changed")
X(eBADCHECKSUM,               "Page checksum does not match")
X(eINSUFFICIENTMEM,           "Memory limit imposed on function was insufficient")
X(eBADARGUMENT,               "Bad argument or combination of arguments to function")
X(eTWOTRANS,                  "Transaction already attached to thread")
X(eTWOTHREAD,                 "Multiple threads not allowed for this operation")
X(eTWOUTHREAD,                "Multiple update threads not allowed for this operation")
X(eNOTRANS,                   "No active transaction")
X(eINTRANS,                   "In active transaction (not allowed for this operation)")
X(eNOABORT,                   "Logging is turned off -- cannot roll back")
X(eNOTPREPARED,               "Transaction thread is not prepared -- cannot commit or abort")
X(eISPREPARED,                "Transaction thread is prepared  -- cannot do this operaton")
X(eEXTERN2PCTHREAD,           "Transaction is (already) participating in external 2-phase commit ")
X(eNOTEXTERN2PC,              "Transaction is not participating in external 2-phase commit ")
X(eNOSUCHPTRANS,              "Could not find a prepared transaction with given global transaction ID")
X(eTHREADMAPFULL,             "No more bits for thread maps")
X(eNOTPARENTLOCK,             "Invalid parent lock type for lockid_t::truncate")
X(eBADLOCKMODE,               "Invalid lock mode")
X(eLOCKTIMEOUT,               "Lock timeout")
X(eNOTBLOCKED,                "Smthread is not blocked")
X(eDEADLOCK,                  "Deadlock detected")
X(eBADCCLEVEL,                "Unsupported concurrency control level")
X(eRETRY,                     "Retry the request (used internally)")
X(eGOODRETRY,                 "Retry, but had some progress (used internally)")
X(eLOCKRETRY,                 "Retry related to locks (used internally)")
X(eTOOMANYRETRY,              "This IS an error and can be thrown to user")
X(eCANTWHILEACTIVEXCTS,       "Can't do to volume while there are active transactions")
X(eLISTTOOLONG,               "Too many items in list")
X(eNOHANDLE,                  "Missing coordinator handle")
X(eLOGVERSIONTOONEW,          "Log created with newer incompatible server")
X(eLOGVERSIONTOOOLD,          "Log created with older incompatible server")
X(eBADMASTERCHKPTFORMAT,      "Bad format for master checkpoint")
X(eABORTED,                   "Transaction aborted by another thread")
X(eLOGSPACEWARN,              "Log space warning (not necessarily out)")
X(eBADCOMPENSATION,           "Log could not apply requested compensation")
X(eAPPENDFILEINOSCAN,         "Append_file_i does not support scanning")
X(eINVALIDHINT,               "Invalid cluster hint ")
X(eDUAUDITFAILED,             "Audit failed for du statistics")
X(ePINACTIVE,                 "Thread has something pinned")
X(eHOTPAGE,                   "Another thread pinned this page in the buffer pool")
X(eBPFORCEFAILED,             "Could not force all the necessary pages from the buffer pool")
X(eBRKKEYCMPNOTIMPL,          "Sort key is broken across pages -- case not implemented")
X(eWRITEORDERLOOP,            "Causes a loop in write order dependency")
X(eLIL_TOOMANYVOL_XCT,        "Accessing too many volumes in one transaction")
X(eLIL_TOOMANYST_XCT,         "Accessing too many stores in one transaction")
X(eBF_DIRECTFIX_SWIZZLED_PTR, "Requested a direct page fix with swizzled pointer")
