all: util core sched stages workload tests server

util:
	cd ../
	cd ..; make lib/libutil.a

core:
	cd ../
	cd ..; make lib/libcore.a

sched:
	cd ../
	cd ..; make lib/libscheduler.a

stages:
	cd ../
	cd ..; make lib/libstages.a

workload:
	cd ../
	cd ..; make lib/libworkload.a

tests:
	cd ../
	cd ..; make tests

server:
	cd ../
	cd ..; make qpipe

clean:
	cd ../
	cd ..; make clean

