/**
 * Platform-dependent definitions.
 * Don't use '//' for comments in this file as this file is used
 * by C compilers too (it will cause an error on Sun C compiler).
 */

/**
 * platform-independent settings.
 * these are generated by CMake from shore-config-env.h.cmake
 * and placed in build-folder/config.
 */
#ifdef SHORE_CONFIG_ENV_H_PATH /* used for SM_PAGESIZE, etc */
#include SHORE_CONFIG_ENV_H_PATH
#else
#include "shore-config-env.h"
#endif

/** common definitions for all platforms. */

/* include tracing code? */
#define TRACECODE 1

/* Version number of package */
#define VERSION "1.0"

/* track return-code checking */
#define W_DEBUG_RC 0

#if (defined(_LARGEFILE_SOURCE) && defined(_FILE_OFFSET_BITS)) || defined(ARCH_LP64)
#define LARGEFILE_AWARE
#endif


#if TRACECODE==1
#define W_TRACE
#endif

/* Opposite to WORDS_BIGENDIAN. Check this after "#ifndef WORDS_BIGENDIAN"
   to make sure you do have a valid config.h in include path. */
#ifndef WORDS_BIGENDIAN
#define WORDS_LITTLEENDIAN
#endif // WORDS_BIGENDIAN
