#!/bin/sh 

## instructions:
## go to the output directory (dox)
## cp -r html converted
## cd html
## find . -type f -exec fgrep -q "/home/nhall" {} \; -exec echo {} \; > & ../list

## from that list file, strip off the ./ from the front of the
## file names and append <space>\ to the end
## and you have the list to insert between the "for" and the "do" lines,
## below:

for FILE in  \
d5/d98/w__form_8cpp-source.html \
d5/dd0/vid__t_8h-source.html \
d5/d54/stid__t_8cpp-source.html \
d5/d96/sort_8h-source.html \
d5/d25/classvtable__func.html \
d5/dc1/pin_8h-source.html \
d5/d5d/devid__t_8h-source.html \
d5/de1/classopaque__quantity.html \
d5/d88/w__debug_8h-source.html \
d5/d19/structocc__rwlock.html \
d5/d5b/classlatch__t.html \
dir_ff5597eff5bf2afe4bf6bec877c08348.html \
d0/d67/lsn_8cpp-source.html \
d0/d29/nbox_8cpp-source.html \
d0/d54/w__form_8h-source.html \
d0/d9a/w__strstream_8h-source.html \
d0/d20/common__tmpl_8cpp-source.html \
d0/d10/structw__error__info__t.html \
d0/d9e/classw__list__i.html \
d0/d79/w__listm_8cpp-source.html \
d0/d41/classsortorder.html \
d0/deb/lid__t_8h-source.html \
d0/d26/errlog_8h-source.html \
d0/de9/vtable_8h-source.html \
d0/dda/classlogstream.html \
d0/d9b/stid__t_8h-source.html \
d0/d6b/structlockid__t_1_1user4__t.html \
d0/d34/classlockid__t.html \
dir_9a74d9245097bf078e64cd41d322b2c9.html \
dd/dc8/classsthread__stats.html \
dd/dbf/w__bitmap_8cpp-source.html \
dd/d60/classauto__release__t_3_01pthread__mutex__t_01_4.html \
dd/d71/w__hashing_8h-source.html \
dd/d30/classauto__release__t_3_01w__pthread__lock__t_01_4.html \
dd/d0b/classshore__compat_1_1strstreambuf.html \
dd/d85/classw__ostrstream__buf.html \
dd/d85/classw__stat__t.html \
dd/d01/structatomic__preallocated__pool.html \
dd/d03/stcore__pthread_8h-source.html \
dd/de8/classw__link__t.html \
dd/d4c/store__latch__manager_8cpp-source.html \
dd/da2/w__rc_8cpp-source.html \
dd/dab/lid__t_8cpp-source.html \
dd/de1/classw__hash__i.html \
dd/dc5/classstore__latch__manager.html \
dd/d7a/classw__istrstream.html \
dd/d73/sthread__vtable__enum_8h-source.html \
dd/dcd/sm__vas_8h.html \
dd/ded/classsthread__t.html \
dd/d93/w__base_8h.html \
dd/d13/classappend__file__i.html \
dir_184614dd8992d95a71c4340453ddccfc.html \
df/d67/gethrtime_8h-source.html \
df/dc9/sm__vas_8h-source.html \
df/d32/classxct__t.html \
df/dfa/classxct__i.html \
df/d77/os__types_8h-source.html \
df/d8b/w__bitvector_8h-source.html \
df/d0c/classlatch__holder__t.html \
df/dd2/tpmcs__lock_8h-source.html \
df/dd5/classw__ostrstream.html \
df/d8a/scan_8h-source.html \
df/dac/devid__t_8cpp-source.html \
df/dec/classw__hash__t.html \
df/d76/classoption__file__scan__t.html \
df/dda/sthread_8cpp-source.html \
df/d3e/kvl__t_8cpp-source.html \
df/d15/structw__pthread__lock__t.html \
d1/d4b/structfill2.html \
d1/d4a/classw__list__base__t.html \
d1/d4d/w_8h-source.html \
d1/df4/bitmap_8cpp-source.html \
d1/dfc/sort__s_8h-source.html \
d1/d0d/w__opaque_8h-source.html \
d1/dbb/structssm__sort_1_1key__info__t.html \
d1/d08/smstats_8h-source.html \
d1/d0c/structdevid__t.html \
d1/dff/classw__bitmap__t.html \
d1/d26/umemcmp_8h-source.html \
d1/d21/atomic__class__pool_8h-source.html \
d1/d8a/gethrtime_8cpp-source.html \
d1/d43/vtable__sthread_8cpp-source.html \
d1/d00/sdisk__unix_8cpp-source.html \
d1/d06/latch_8cpp-source.html \
d1/dcb/w__defines_8h-source.html \
d1/d8e/lock__s_8h-source.html \
d1/db1/class_thread_func.html \
d1/da9/classsm__save__point__t.html \
d1/d83/w__rc_8h.html \
d2/dc8/classscan__index__i.html \
d2/dfa/structcritical__section_3_01_lock_01_5_6_01_4.html \
d2/d3d/vtable_8cpp-source.html \
d2/d1c/classssm__sort_1_1skey__t.html \
d2/d85/block__alloc_8h-source.html \
d2/dd1/classnbox__t.html \
d2/d03/w__debug_8cpp-source.html \
d2/d2b/structlockid__t_1_1user3__t.html \
d2/d63/sdisk__unix_8h-source.html \
d2/dc1/vec__t_8cpp-source.html \
d2/da3/stime_8h-source.html \
d2/d14/w__shore__alloc_8h-source.html \
d2/d33/classsthread__init__t.html \
d2/d62/option_8h-source.html \
d2/d6b/classsthread__base__t.html \
d2/d19/classlsn__t.html \
d2/d37/w__hash_8h-source.html \
d6/d9d/structtatas__lock.html \
d6/dbf/errlog__s_8h-source.html \
d6/d09/tls_8h-source.html \
d6/d0d/classsm__stats__t.html \
d6/d38/w__compat__strstream_8h-source.html \
d6/de0/valgrind__help_8cpp-source.html \
d6/d14/classauto__release__w__t.html \
d6/d0f/structlockid__t_1_1user2__t.html \
d6/def/bitmap_8h-source.html \
d6/d3c/w__debug_8h.html \
d6/dbd/sm__base_8h-source.html \
d6/d7f/errlog_8cpp-source.html \
files.html \
de/d94/w__hash_8h.html \
de/d2a/classssm__sort_1_1factory__t.html \
de/d81/sm__base_8h.html \
de/dca/srwlock_8h-source.html \
de/d0b/struct_v_e_c__t.html \
de/d01/sdisk_8cpp-source.html \
de/d87/classscan__rt__i.html \
de/d5d/structtls__tricks_1_1tls__blob.html \
de/dc5/tid__t_8cpp-source.html \
de/d4f/classshore__compat_1_1istrstream.html \
de/dc3/smthread_8h-source.html \
de/d1b/vec__t_8h-source.html \
de/d9f/classw__rc__i.html \
de/d2e/nbox_8h-source.html \
de/d3a/option_8cpp-source.html \
de/d7f/w__gettimeofday_8h-source.html \
de/db9/w__workaround_8h.html \
d7/d68/sthread__core__pthread_8cpp-source.html \
d7/d57/w__stream_8h-source.html \
d7/d2a/classsmthread__t.html \
d7/d54/tls_8cpp-source.html \
d7/dae/classw__vbase__t.html \
d7/da2/classoption__group__t.html \
d7/d5d/classw__debug.html \
d7/d14/classssm__sort_1_1key__location__t.html \
d7/d14/sthread__stats_8cpp-source.html \
d7/dab/basics_8cpp-source.html \
d7/d50/classssm__sort_1_1sort__keys__t.html \
d7/dd3/w__heap_8h-source.html \
d7/d45/w__base_8cpp-source.html \
d7/d6e/classholder__search.html \
d7/d5e/structcompile__time__assert.html \
d7/d0a/mcs__lock_8h-source.html \
d7/d3e/classatomic__thread__map__t.html \
d9/d85/structatomic__class__pool.html \
d9/d10/vec__mkchunk_8cpp-source.html \
d9/dee/classsm__stats__info__t.html \
d9/da4/classcvec__t.html \
d9/d4e/w__findprime_8h-source.html \
d9/dd2/w__workaround_8h-source.html \
d9/d26/classw__ascend__list__t.html \
d9/d6e/classoption__t.html \
d9/dcb/w__heap_8cpp-source.html \
d9/dcb/classholders__print.html \
d9/dbd/structkvl__t.html \
d9/dda/classpin__i.html \
d9/d7f/classmcs__rwlock.html \
d9/d12/classw__auto__delete__array__t.html \
d9/da0/classw__base__t.html \
search.idx \
d3/d54/w__minmax_8h-source.html \
d3/d2f/classbf__htab__stats__t.html \
d3/d65/structlockid__t_1_1user1__t.html \
d3/dba/sthread_8h-source.html \
d3/dca/lexify_8h-source.html \
d3/d30/class_heap.html \
d3/dfc/classsm__quark__t.html \
d3/d8b/classsm__store__info__t.html \
d3/d10/largefile__aware_8h-source.html \
d3/d3f/structvid__t.html \
d3/d25/lsn_8h-source.html \
d3/d17/io_8cpp-source.html \
d3/d38/stime_8cpp-source.html \
d3/dc1/__random_8cpp-source.html \
d3/db2/valgrind__help_8h-source.html \
d3/de1/sthread_8h.html \
d3/d3b/w__input_8cpp-source.html \
d3/dd2/structfill1.html \
d3/d7a/w__form__base_8cpp-source.html \
d3/d18/atomic__container_8h-source.html \
d3/d76/classvtable__t.html \
d3/d76/w__error_8cpp-source.html \
d8/db3/structtls__tricks_1_1tls__manager__schwarz.html \
d8/d4b/classauto__release__t.html \
d8/d94/structlvid__t.html \
d8/d4a/w__getopt_8cpp-source.html \
d8/d69/smthread_8h.html \
d8/dfa/w__rusage_8h-source.html \
d8/d90/classw__hashing_1_1hash2.html \
d8/d22/store__latch__manager_8h-source.html \
d8/d92/w__list_8h.html \
d8/ddb/classvec__t.html \
d8/de7/classunsafe__list__dummy__lock__t.html \
d8/d25/kvl__t_8h-source.html \
d8/de8/struct_compile_time_assertion_3_01true_01_4.html \
d8/d07/tls_8h.html \
d8/db2/classblock__alloc.html \
d8/d4e/classsmlevel__0.html \
d8/dc5/classatomic__container.html \
d8/d95/classauto__release__r__t.html \
d8/ddf/classw__keyed__list__t.html \
d8/d1d/w__stat_8h-source.html \
d8/d8a/w__list_8h-source.html \
d8/d12/classtid__t.html \
d8/d78/structvec__pair__t.html \
dir_057c78c0d01d30fe5600b42b19a200c4.html \
dc/d68/classw__list__t.html \
dc/df4/structfill3.html \
dc/d77/w__autodel_8h-source.html \
dc/d7d/w__error_8h-source.html \
dc/dc2/classw__error__t.html \
dc/ddb/classw__bitvector__t.html \
dc/d0d/xct_8h-source.html \
dc/d6c/classw__hashing_1_1uhash.html \
dc/deb/os__fcntl_8h-source.html \
dc/d18/classholder__list.html \
dc/db1/structfill4.html \
dc/df8/classshore__compat_1_1ostrstream.html \
dc/de4/classssm__sort_1_1key__cookie__t.html \
da/d1c/classsort__stream__i.html \
da/db2/w__getopt_8h-source.html \
da/dd2/os__interface_8h-source.html \
da/d18/sthread__stats_8h.html \
da/d44/classss__m.html \
da/d44/basics_8h-source.html \
da/d46/sm_8h-source.html \
da/d47/auto__release_8h-source.html \
da/dcc/w__findprime_8cpp-source.html \
da/d5b/structstid__t.html \
db/d2d/class_smthread_func.html \
db/d29/sthread__stats_8h-source.html \
db/d27/classrand48.html \
db/d4a/classvtable__row__t.html \
db/d28/w__rc_8h-source.html \
db/d22/classoption__stream__scan__t.html \
db/d05/tid__t_8h-source.html \
db/d59/classalloca_n.html \
db/dc7/classw__rc__t.html \
db/d66/structssm__sort_1_1sort__parm__t.html \
db/dbb/atomic__templates_8h-source.html \
db/d4c/structcompare__snum__t.html \
db/de6/hostname_8h-source.html \
db/d9c/classscan__file__i.html \
db/dcd/structssm__sort_1_1generic___c_s_k_f__cookie.html \
db/dec/srwlock_8cpp-source.html \
db/d3e/structsm__config__info__t.html \
db/d46/rand48_8cpp-source.html \
dir_a16d5816e087c7e428b1c1294e42443b.html \
d4/d57/vid__t_8cpp-source.html \
d4/d4a/classw__list__const__i.html \
d4/da6/w__bitmap_8h-source.html \
d4/df6/sm__int__3_8h-source.html \
d4/dc7/latch_8h-source.html \
d4/d17/class_err_log.html \
d4/dc5/classw__auto__delete__t.html \
d4/dc5/rand48_8h-source.html \
d4/d45/classssm__sort_1_1object__t.html \
d4/d45/w__compat__strstream_8cpp-source.html \
d4/dbe/classtls__tricks_1_1tls__manager.html \
d4/df9/structholder__list_1_1iterator.html \
d4/d3e/classzvec__t.html \
d4/d3e/w__base_8h-source.html \
d4/dcc/sdisk_8h-source.html \
d4/dcc/classw__descend__list__t.html \
; do
	 echo mkdir -p ../converted/`dirname $FILE`
     mkdir -p ../converted/`dirname $FILE`
     sed 's=/home/nhall=..=g' $FILE > ../converted/$FILE
done
